//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipbobFinalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int userID { get; set; }
        public string trackingID { get; set; }
        public int orderID { get; set; }
        public string street { get; set; }
        public string state { get; set; }
        public int zipCode { get; set; }
    
        public virtual user user { get; set; }
    }
}
