//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipbobFinalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.orders = new HashSet<order>();
        }
    
        public int userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
    }
}
